version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - pip install cfn-lint
  build:
    commands:
      - npm install
      - npm run unit-test
      - ./publish.sh